coverage:
  precision: 1
  range: "75...90"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%
github_checks:
  annotations: true
ignore:
  - benchmark/**
  - docs/**
  - springin/** # ignore the springin directory due to deprecated code
  - registry/crypto/** # ignore the registry/crypto due to deprecated code
comment:
  behavior: new
  require_changes: true
